backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: src/images/
public_folder: ../images/

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }        
      - { label: 'Publish Date', name: 'date', widget: 'date'}      
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }      
      - { label: 'Path', name: 'path', widget: 'string', default: '/blog/xx' }
      - { label: 'Blog post content', name: 'body', widget: 'markdown' }

